/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AnalyticsEvent } from '../models/analytics-event';
export interface Analytics {
  onclick?: AnalyticsEvent;
  onload?: AnalyticsEvent;
  onsent?: AnalyticsEvent;
}
