/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Gif } from '../models/gif';
export type Emoji = Gif & {

/**
 * The number of variations associated with the emoji
 */
'variation_count'?: number;
};

