/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Gif } from '../models/gif';
import { Meta } from '../models/meta';
import { Pagination } from '../models/pagination';
export interface GifResponse {
  data?: Array<Gif>;
  meta?: Meta;
  pagination?: Pagination;
}
