/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ImageRendition {
  frames?: string;
  height?: string;
  mp4?: string;
  mp4_size?: string;
  size?: string;
  url?: string;
  webp?: string;
  webp_size?: string;
  width?: string;
}
