/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImageRendition } from '../models/image-rendition';

/**
 * Object containing all available renditions of the GIF
 */
export interface Images {
  downsized?: ImageRendition;
  downsized_large?: ImageRendition;
  downsized_medium?: ImageRendition;
  downsized_small?: ImageRendition;
  downsized_still?: ImageRendition;
  fixed_height?: ImageRendition;
  fixed_height_downsampled?: ImageRendition;
  fixed_height_small?: ImageRendition;
  fixed_height_small_still?: ImageRendition;
  fixed_height_still?: ImageRendition;
  fixed_width?: ImageRendition;
  fixed_width_downsampled?: ImageRendition;
  fixed_width_small?: ImageRendition;
  fixed_width_small_still?: ImageRendition;
  fixed_width_still?: ImageRendition;
  looping?: ImageRendition;
  original?: ImageRendition;
  original_still?: ImageRendition;
  preview?: ImageRendition;
  preview_gif?: ImageRendition;
}
