/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Meta {

  /**
   * HTTP Response Message
   */
  msg: string;

  /**
   * A unique ID paired with this response from the API
   */
  response_id?: string;

  /**
   * HTTP Response Code
   */
  status: number;
}
