/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface User {
  avatar_url?: string;
  banner_url?: string;
  display_name?: string;
  profile_url?: string;
  username?: string;
}
