/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GifResponse } from '../../models/gif-response';

export interface GetGifsByIds$Params {
  api_key: string;

/**
 * ID multipli separati da virgola
 */
  ids: string;
}

export function getGifsByIds(http: HttpClient, rootUrl: string, params: GetGifsByIds$Params, context?: HttpContext): Observable<StrictHttpResponse<GifResponse>> {
  const rb = new RequestBuilder(rootUrl, getGifsByIds.PATH, 'get');
  if (params) {
    rb.query('api_key', params.api_key, {});
    rb.query('ids', params.ids, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GifResponse>;
    })
  );
}

getGifsByIds.PATH = '/gifs';
