/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GifResponse } from '../../models/gif-response';

export interface SearchGifs$Params {
  api_key: string;

/**
 * Il termine di ricerca
 */
  q: string;
  limit?: number;
  offset?: number;
}

export function searchGifs(http: HttpClient, rootUrl: string, params: SearchGifs$Params, context?: HttpContext): Observable<StrictHttpResponse<GifResponse>> {
  const rb = new RequestBuilder(rootUrl, searchGifs.PATH, 'get');
  if (params) {
    rb.query('api_key', params.api_key, {});
    rb.query('q', params.q, {});
    rb.query('limit', params.limit, {});
    rb.query('offset', params.offset, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GifResponse>;
    })
  );
}

searchGifs.PATH = '/gifs/search';
