/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getGifsByIds } from '../fn/operations/get-gifs-by-ids';
import { GetGifsByIds$Params } from '../fn/operations/get-gifs-by-ids';
import { getTrendingGifs } from '../fn/operations/get-trending-gifs';
import { GetTrendingGifs$Params } from '../fn/operations/get-trending-gifs';
import { GifResponse } from '../models/gif-response';
import { searchGifs } from '../fn/operations/search-gifs';
import { SearchGifs$Params } from '../fn/operations/search-gifs';

@Injectable({ providedIn: 'root' })
export class ApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `searchGifs()` */
  static readonly SearchGifsPath = '/gifs/search';

  /**
   * Cerca GIFs per termine.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchGifs()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchGifs$Response(params: SearchGifs$Params, context?: HttpContext): Observable<StrictHttpResponse<GifResponse>> {
    const obs = searchGifs(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Cerca GIFs per termine.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchGifs$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchGifs(params: SearchGifs$Params, context?: HttpContext): Observable<GifResponse> {
    const resp = this.searchGifs$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<GifResponse>): GifResponse => r.body)
    );
  }

  /** Path part for operation `getTrendingGifs()` */
  static readonly GetTrendingGifsPath = '/gifs/trending';

  /**
   * Ottieni le GIF di tendenza.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTrendingGifs()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTrendingGifs$Response(params: GetTrendingGifs$Params, context?: HttpContext): Observable<StrictHttpResponse<GifResponse>> {
    const obs = getTrendingGifs(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Ottieni le GIF di tendenza.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTrendingGifs$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTrendingGifs(params: GetTrendingGifs$Params, context?: HttpContext): Observable<GifResponse> {
    const resp = this.getTrendingGifs$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<GifResponse>): GifResponse => r.body)
    );
  }

  /** Path part for operation `getGifsByIds()` */
  static readonly GetGifsByIdsPath = '/gifs';

  /**
   * Ottieni GIF specifiche tramite ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getGifsByIds()` instead.
   *
   * This method doesn't expect any request body.
   */
  getGifsByIds$Response(params: GetGifsByIds$Params, context?: HttpContext): Observable<StrictHttpResponse<GifResponse>> {
    const obs = getGifsByIds(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Ottieni GIF specifiche tramite ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getGifsByIds$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getGifsByIds(params: GetGifsByIds$Params, context?: HttpContext): Observable<GifResponse> {
    const resp = this.getGifsByIds$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<GifResponse>): GifResponse => r.body)
    );
  }

}
