/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { SearchGifs$Params as SearchGifs$Params } from './fn/operations/search-gifs';
export { searchGifs as searchGifs } from './fn/operations/search-gifs';
export type { GetTrendingGifs$Params as GetTrendingGifs$Params } from './fn/operations/get-trending-gifs';
export { getTrendingGifs as getTrendingGifs } from './fn/operations/get-trending-gifs';
export type { GetGifsByIds$Params as GetGifsByIds$Params } from './fn/operations/get-gifs-by-ids';
export { getGifsByIds as getGifsByIds } from './fn/operations/get-gifs-by-ids';
